### ISSUE TITLE
Message Users

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-pitcherplants#18]
## User Story
As a user, I want to easily be able to tell who sent each message.

## AC
**WHEN** the page loads
**THEN** i should see messages
**AND** each message should show who wrote that message

## Dev notes
* When you add a message you should pull the value from the radio button and put that value in the `addMessage` function.
* In the addMessage function, the function in the comments below should be used to insert the value of the radio button into a domString variable and printed out.

**Comment by StevenZelenak** [comment]
```js
$('#myForm input').on('change', function() {
   alert($('input[name=radioName]:checked', '#myForm').val()); 
});``

**Comment by StevenZelenak** [comment]
----------------------------------------------------------------------------------------
Example:
```html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<form id="myForm">
  <input type="radio" name="radioName" value="1" /> 1 <br />
  <input type="radio" name="radioName" value="2" /> 2 <br />
  <input type="radio" name="radioName" value="3" /> 3 <br />
</form>``
