### ISSUE TITLE
Mockup

### ISSUE THREAD

**Issue by StevenZelenak** [nss-evening-cohort-11/chatty-pitcherplants#20]
## User Story
As a developer, you should see the lo-fi wireframes of the site architecture

## AC
WHEN you look at this card
THEN you should see screenshots of the layout of each page 
AND you'll be ready to code!

## Dev Notes
* Add wireframes for the page
* Icon
* input fields
* check boxes
* radio buttons 
* clear button
* add button

**Comment by olamide87** [comment]
![image](https://user-images.githubusercontent.com/59629698/76269611-5ca57e00-6240-11ea-8432-5d2c23a63c0c.png)
