### ISSUE TITLE
Message Limit

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-pitcherplants#7]
## User Story
As a user, I have a short attention span, and only want to see the last 20 messages.

## AC
**Given** A user navigates to your page
**Then** they should only see the last 20 messages

## Dev Notes
We will create a function that will only load the last 20 messages from the message array which is located in messageData.js
the function will be called  latestMessages. This function will need to be exported from messageData.js and imported into display Message.js

```const lastMessages = () => {
const number = messages.length-20
messages.slice(0, number);
};```

**Comment by ToddSpainhour** [comment]
.slice(where to start, where to end)

arr.slice(arr.length - 20, arr.length)

this line was returning the last 20 items (objects or strings) from the array no matter how many were there. I have the whole example saved if you need to see it in action.
